# Configuration file for Travis-CI testing
# Test using <http://lint.travis-ci.org/>

language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "0.13"
env:
  - MAPCACHE_COMMIT=11e85095a39010f953b34077b7f0824e234e9423 # minimum supported version
  - MAPCACHE_COMMIT=rel-1-0-0  # v1.0.0
  - MAPCACHE_COMMIT=rel-1-2-0  # v1.2.0
  - MAPCACHE_COMMIT=rel-1-2-1  # v1.2.1
  - MAPCACHE_COMMIT=           # repository HEAD
matrix:
  fast_finish: true
  # allow unstable versions to fail
  allow_failures:
    - node_js: "0.13"
    - env: MAPCACHE_COMMIT=
before_install:
  - sudo apt-get install libapr1-dev libaprutil1-dev # mapcache dependencies
  - sh ./tools/install-deps.sh /tmp $MAPCACHE_COMMIT # install the dependencies
